---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: nginx:1.21
    kbld.carvel.dev/origins: |
      - resolved:
          tag: "1.21"
          url: nginx:1.21
  image: index.docker.io/library/nginx@sha256:2d17cc4981bf1e22a87ef3b3dd20fbb72c3868738e3f307662eb40e2630d4320
kind: ImagesLock
